<?php

namespace app\models;

use himiklab\thumbnail\EasyThumbnailImage;
use Yii;

/**
 * This is the model class for table "file".
 *
 * @property int $id
 * @property string|null $filename
 * @property int|null $created_at
 */
class File extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'file';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at'], 'integer'],
            [['filename'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'filename' => 'Название',
            'created_at' => 'Дата добавления',
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param int|null $width
     * @param int|null $height
     * @param string $type
     * @return false|string
     */
    public function getThumb(int $width = null, int $height = null, string $type = 'original')
    {
        $path = Yii::getAlias('@app/web/uploads/') . $this->filename;
        if (!file_exists($path)) {
            return false;
        }

        if ($type == 'original') {
            return '/uploads/' . $this->filename;
        }

        if (!$width) $width = 300;
        if (!$height) $height = 300;

        return EasyThumbnailImage::thumbnailImg($path, $width, $height, EasyThumbnailImage::THUMBNAIL_OUTBOUND);
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return '/site/file?id=' . $this->id;
    }
}
